---
- name: Packages
  dnf:
    name: python3-requests-oauthlib
    state: present
  tags:
    - packages

- block:
    - name: Openshift API Log in (obtain access token)
      k8s_auth:
        host: "{{ openshift['api'] }}"
        username: "{{ openshift['admin_user'] }}"
        password: "{{ openshift['admin_pass'] }}"
        validate_certs: "{{ openshift['validate_api_certs'] | default(False) }}"
      check_mode: False
      register: k8s_auth_results

    - name: Setting Logging
      import_tasks: logging.yml
      tags:
        - logging

    - name: Setting MachineSets
      import_tasks: machinesets_vmware.yml
      tags:
        - machinesets

  always:
    - name: If login succeeded, try to log out (revoke access token)
      k8s_auth:
        api_key: "{{ k8s_auth_results['k8s_auth']['api_key'] }}"
        host: "{{ openshift['api'] }}"
        state: absent
        validate_certs: "{{ openshift['validate_api_certs'] | default(False) }}"
      check_mode: False
      when: k8s_auth_results['k8s_auth']['api_key'] is defined
